# Generated by Django 5.1.3 on 2025-08-31 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='quickbooks', max_length=100)),
                ('connection_type', models.CharField(choices=[('Online', 'online'), ('On premise', 'offline'), ('SH', 'sh')], default='online', max_length=10)),
                ('version', models.CharField(choices=[('v15', 'v15'), ('v16', 'v16'), ('v17', 'v17')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OdooUserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('port', models.IntegerField(default=80)),
                ('database', models.CharField(max_length=100)),
                ('database_uuid', models.CharField(blank=True, max_length=800, null=True)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('connected_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_app', to='app.connectedapp')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odoo_erp.odooconnector')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisation')),
            ],
            options={
                'unique_together': {('connector', 'organisation', 'database_uuid')},
            },
        ),
    ]
