# Generated by Django 5.1.3 on 2025-09-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentplan_payment_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
