# Generated by Django 5.1.3 on 2025-09-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentplan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
