# Generated by Django 5.1.3 on 2025-08-31 17:24

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZimraConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='zimra', max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, default='ZW', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZimraFiscalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ZimraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_registration_form', models.FileField(blank=True, null=True, upload_to='files/')),
                ('zimra_registration_contact_email', models.EmailField(blank=True, default='tsilongwe4324234@zimra.co.zw', max_length=100, null=True)),
                ('taxpayer_tin_number', models.CharField(blank=True, max_length=100, null=True)),
                ('taxpayer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('taxpayer_vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_version_no', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activation_key', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_key', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('receipt_counter', models.IntegerField(blank=True, null=True)),
                ('receipt_global_counter', models.IntegerField(blank=True, null=True)),
                ('receipt_previous_hash', models.TextField(blank=True, default='', null=True)),
                ('file_counter', models.IntegerField(blank=True, null=True)),
                ('zimra_api_device_information', models.JSONField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisation')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zimra.zimraconnector')),
            ],
        ),
    ]
