# Generated by Django 5.1.3 on 2025-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zimraconfig',
            name='zimra_invoice_validation_errors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
