# Generated by Django 5.1.3 on 2025-09-09 09:09

import zimra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimra', '0005_zimraconfig_zimra_invoice_validation_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zimraconfig',
            name='zimra_invoice_validation_errors',
            field=models.JSONField(blank=True, default=zimra.models.default_zimra_invoice_validation_errors, null=True),
        ),
    ]
