# Generated by Django 5.1.3 on 2025-09-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimra', '0006_alter_zimraconfig_zimra_invoice_validation_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zimraconfig',
            name='file_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zimraconfig',
            name='receipt_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zimraconfig',
            name='receipt_global_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
