# Generated by Django 5.1.3 on 2025-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimra', '0007_alter_zimraconfig_file_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zimraconfig',
            name='zimra_fiscal_day_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
