# Generated by Django 5.1.3 on 2025-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='hs_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
