# Generated by Django 5.1.3 on 2025-09-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoiceproduct_hs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], default='invoice', max_length=100),
        ),
    ]
