# Generated by Django 5.1.3 on 2025-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
