# Generated by Django 5.1.3 on 2025-09-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_invoice_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='qr_code',
            new_name='qr_code_url',
        ),
    ]
