# Generated by Django 5.1.3 on 2025-09-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_qr_code_invoice_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qr_code_sent',
            field=models.BooleanField(default=False),
        ),
    ]
