# Generated by Django 5.1.3 on 2025-09-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_invoice_qr_code_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='qr_code_sent',
        ),
    ]
