# Generated by Django 5.1.3 on 2025-09-13 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_invoice_qr_code_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
