# Generated by Django 5.1.3 on 2025-09-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_invoice_document_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='document_date',
        ),
    ]
