# Generated by Django 5.1.3 on 2025-08-31 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickbookConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='quickbooks', max_length=100)),
                ('connection_type', models.CharField(choices=[('Online', 'online'), ('Desktop', 'desktop')], default='online', max_length=10)),
                ('region', models.CharField(default='GB', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuickbookUserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickbook.quickbookconnector')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisation')),
            ],
            options={
                'unique_together': {('connector', 'organisation', 'realm_id')},
            },
        ),
    ]
