"""
Django settings for taxman project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


CSRF_TRUSTED_ORIGINS = [
    'https://hopefully-destined-amoeba.ngrok-free.app',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # <--- Added for whitenoise
    'django.contrib.staticfiles',
    # third party applications
    # "tailwind",
    # "django_browser_reload",
    'rest_framework',
    "verify_email.apps.VerifyEmailConfig",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_crontab',
    # custom apps
    'app',
    'quickbook',
    'odoo_erp',
    'zimra',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- Added for whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django_browser_reload.middleware.BrowserReloadMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'app.middleware.disable_csrf',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ROOT_URLCONF = 'taxman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taxman.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Feel free to alter this value to suit your needs.
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Harare'
USE_TZ = True

USE_I18N = True

USE_TZ = True

# Email Django-Verify-Email
# HTML_MESSAGE_TEMPLATE = "path/to/html_template.html"

# VERIFICATION_SUCCESS_TEMPLATE = "path/to/success.html"

# VERIFICATION_FAILED_TEMPLATE = "path/to/failed.html"

# REQUEST_NEW_EMAIL_TEMPLATE = "path/to/email.html"

# LINK_EXPIRED_TEMPLATE = 'path/to/expired.html'

# NEW_EMAIL_SENT_TEMPLATE  = 'path/to/new_email_sent.html'

# REQUEST_NEW_EMAIL_TEMPLATE = 'mytemplates/mycustomtemplate.html'

# EXPIRE_AFTER = "5h"

# MAX_RETRIES = 5

SUBJECT = 'TaxMan Email Verification'

# tailwind django settings
# TAILWIND_APP_NAME = 'theme'
# NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

# AllAuth Settings
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "assanisaidi73@gmail.com"
EMAIL_HOST_PASSWORD = "leyzysbbxypzfdfn"

DEFAULT_FROM_EMAIL = 'assanisaidi73@gmail.com'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


MEDIA_URL = '/files/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'files')

# Django crontab configurations
CRONJOBS = [
    # run every day at 9pm (21:00)
    ('0 21 * * *', 'zimra.cron.auto_close_fiscal_day'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'

# ------------------- CUSTOM SETTINGS -------------------------------

# QUICKBOOKS API VARIABLES
QUICKBOOKS_BASE_URL = "https://sandbox-quickbooks.api.intuit.com/v3"
QUICKBOOKS_CLIENT_ID = "AB46D8zuDzivVXr1oWv7KwGMuRh2zy91fRiWLi6Z3PCr5ffFge"
QUICKBOOKS_CLIENT_SECRET = "PE6JJda2dfNLYVKiflaA7lBmz7sCSiKe5WhCL6QV"
QUICKBOOKS_ENVIROMENT = "sandbox"
QUICKBOOKS_REDIRECT_URL = "https://hopefully-destined-amoeba.ngrok-free.app/quickbooks/validate"
QUICKBOOKS_REFRESH_TOKEN_COOKIE_NAME = 'quickbooks_refresh_token'
QUICKBOOKS_REALM_ID_COOKIE_NAME = 'quickbooks_realm_id'
QUICKBOOKS_WEEBHOOK_VERIFIER_TOKEN = "d599caf6-2ff3-41a6-8ce7-0e61b610de12"
ODOO_WEBHOOK_URL = "https://hopefully-destined-amoeba.ngrok-free.app/odoo/fiscalise"

# ZIMRA API VARIABLES
ZIMRA_BASE_URL = "https://fdmsapitest.zimra.co.zw"
ZIMRA_API_VERSION = "v1"

# ECOCASH API VARIABLES (SAFER TO MOVE THESE TO .env)
ECOCASH_CALLBACK_URL="https://hopefully-destined-amoeba.ngrok-free.app/payments/callback/"
ECOCASH_API_KEY="gy0I7Xa2ZfLA7cv_7s0gJP5-Vf4361go"
ECOCASH_API_URL="https://developers.ecocash.co.zw/api/ecocash_pay/api/v2/payment/instant/c2b/sandbox"